name: Security Audit

on:
  # Run weekly on Monday at 00:00 UTC
  schedule:
    - cron: '0 0 * * 1'
  # Allow manual trigger
  workflow_dispatch:
  # Run on pushes to main that modify dependencies
  push:
    branches: [main]
    paths:
      - '**/package.json'
      - 'pnpm-lock.yaml'

jobs:
  audit:
    name: Dependency Audit
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run security audit
        run: pnpm audit --audit-level moderate
        continue-on-error: true

      - name: Check for vulnerabilities
        run: |
          echo "Security audit completed."
          echo "Review any vulnerabilities reported above."
          echo "For production dependencies, consider updating packages with 'pnpm update'."

  license-check:
    name: License Check
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check licenses
        run: |
          echo "Checking package licenses..."
          pnpm licenses list --json > licenses.json || true
          echo "License check completed. Review licenses.json if needed."
        continue-on-error: true
